
[book]

input_filename  = "epub/arthur-conan-doyle_the-sign-of-the-four-mod.epub"
output_dir = "shavian"


words_filename = "words.json"

#phrases_filename = "phrases.txt"

#generate_words_file = true

cover  = "images/cover.jpg"
