
[book]

input_filename  = "../epub/arthur-conan-doyle_the-sign-of-the-four-mod.epub"
output_dir = "../out"


words_filename = "../book-config/arthur-conan-doyle_the-sign-of-the-four/words.json"

#phrases_filename = "../book-config/arthur-conan-doyle_the-sign-of-the-four/phrases.txt"

#generate_words_file = true

cover  = "../book-config/arthur-conan-doyle_the-sign-of-the-four/images/cover.jpg"
