
[book]

input_filename  = "epub/H. G. Wells - Tales of Space and Time - pg27365.epub"
output_dir = "shavian"
words_filename = "words.json"
phrases_filename = "phrases.txt"

cover = "images..cover.jpg"

# All files under this directory will be copied into the epub
# Any existing images with the same name in the epub will be overwritten 
copy_data = "data"

# List of items to omit
#remove_items = [ "colophon.xhtml", "imprint.xhtml", "uncopyright.xhtml", "logo.png", "logo-2x-2x.png"]
#no_transliteration = [ "colophon.xhtml", "imprint.xhtml", "uncopyright.xhtml"]

# Set <dc:date>
dc_date = "2026-10-05T01:02:05Z"

# replace the dc:title element in the metadata,
dc_title = "𐑑𐑱𐑤𐑟 𐑝 𐑕𐑐𐑱𐑕 𐑯 𐑑𐑲𐑥"

# Replaces <dc:identifier> content, or added if it doesn't already existing
dc_identifier = "https://github.com/g-bull/shavian/hg-wells-tales-of-time-and-space"


